# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeschedule',
            old_name='end_schedule_end',
            new_name='end_schedule_time',
        ),
    ]
