# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 14:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171114_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='motime_logs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('time_action', models.TimeField(blank=True, null=True)),
                ('date_action', models.DateField(blank=True, null=True)),
                ('user_action', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.IntegerField(default='01')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.EmployeeDetail')),
            ],
        ),
    ]
