# Generated by Django 2.0 on 2017-12-06 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_timetracker_time_out_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeadpreport',
            name='emp_id',
            field=models.ForeignKey(on_delete=None, to='dashboard.EmployeeDetail'),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='emp_department_ID',
            field=models.ForeignKey(on_delete=None, to='dashboard.EmployeeDepartment'),
        ),
        migrations.AlterField(
            model_name='employeedetail',
            name='emp_position_ID',
            field=models.ForeignKey(on_delete=None, to='dashboard.EmployeePosition'),
        ),
        migrations.AlterField(
            model_name='employeeschedule',
            name='emp_id',
            field=models.ForeignKey(on_delete=None, to='dashboard.EmployeeDetail'),
        ),
        migrations.AlterField(
            model_name='motimelogs',
            name='emp_id',
            field=models.ForeignKey(on_delete=None, to='dashboard.EmployeeDetail'),
        ),
        migrations.AlterField(
            model_name='timetracker',
            name='emp_id',
            field=models.ForeignKey(on_delete=None, to='dashboard.EmployeeDetail'),
        ),
    ]
