# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLogs',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('log_action', models.CharField(blank=True, max_length=255)),
                ('log_date', models.DateField(blank=True, null=True)),
                ('log_time', models.TimeField(blank=True, null=True)),
                ('log_out', models.TimeField(blank=True, null=True)),
                ('overtime', models.IntegerField(blank=True, null=True)),
                ('total_late', models.IntegerField(blank=True, null=True)),
                ('night_def', models.IntegerField(blank=True, null=True)),
                ('lwop', models.IntegerField(blank=True, null=True)),
                ('undertime', models.IntegerField(blank=True, null=True)),
                ('start_break', models.TimeField(blank=True, null=True)),
                ('end_break', models.TimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=30, null=True)),
                ('created_date_time', models.DateTimeField(blank=True, null=True)),
                ('change_by', models.CharField(blank=True, max_length=30, null=True)),
                ('change_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(default='01')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.EmployeeDetail')),
            ],
        ),
    ]
