# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-22 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('holiday_id', models.AutoField(primary_key=True, serialize=False)),
                ('holiday_type', models.CharField(max_length=8)),
                ('holiday_desc', models.CharField(max_length=15)),
                ('holiday_date', models.DateField()),
                ('recurr', models.CharField(max_length=2)),
            ],
        ),
    ]
